site_name: Uncharted Constructs
site_description: Exploring the Frontiers of System Design
site_url: https://osdevisnot.github.io
theme:
  name: material
  palette:
    scheme: slate
    primary: grey
  font:
    text: Work Sans
  features:
    - navigation.tabs
    - navigation.expand
plugins:
  - search
  - blog
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
