site_name: Uncharted Constructs // Tech, Finance, and Life
site_description: Uncharted Constructs explores the intersections of technology, finance, and life. Join me as I navigate system design, programming, smart financial decisions, and the broader complexities of modern living.
site_url: https://osdevisnot.github.io
theme:
  name: material
  palette:
    scheme: slate
    primary: grey
  font:
    text: Work Sans
  features:
    - navigation.tabs
    - navigation.expand
plugins:
  - search
  - blog:
      archive: false
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
