[project]
name = "osdevisnot-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.5.34",
]

[tool.uv]
dev-dependencies = [
    "black>=24.8.0",
]
